name: Run Cloudflare Tunnel for RDP

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: windows-latest
    steps:
      - name: Enable RDP and firewall
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Create or update runneradmin user
        shell: powershell
        run: |
          $securePass = ConvertTo-SecureString $env:WINDOWS_ADMIN_PASSWORD -AsPlainText -Force
          $existing = Get-LocalUser -Name "runneradmin" -ErrorAction SilentlyContinue
          if ($null -eq $existing) {
            New-LocalUser -Name "runneradmin" -Password $securePass -FullName "Runner Admin" -PasswordNeverExpires:$true
          } else {
            Set-LocalUser -Name "runneradmin" -Password $securePass
          }
          try {
            Add-LocalGroupMember -Group "Administrators" -Member "runneradmin" -ErrorAction Stop
          } catch {
            Write-Host "runneradmin already in Administrators."
          }
        env:
          WINDOWS_ADMIN_PASSWORD: ${{ secrets.WINDOWS_ADMIN_PASSWORD }}

      - name: Download cloudflared
        shell: powershell
        run: |
          Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe

      - name: Decode credentials and run tunnel
        shell: powershell
        env:
          CF_TUNNEL_CREDS_B64: ${{ secrets.CF_TUNNEL_CREDS_B64 }}
        run: |
          # Decode credentials JSON
          $creds = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:CF_TUNNEL_CREDS_B64))
          Set-Content -Path credentials.json -Value $creds

          # Run the named tunnel (replace myrdp with your actual tunnel name)
          Start-Process -FilePath .\cloudflared.exe -ArgumentList "tunnel", "run", "myrdp", "--credentials-file", "credentials.json" -NoNewWindow
          Start-Sleep -Seconds 5
          .\cloudflared.exe tunnel list
