name: Free RDP via Cloudflare

on:
  workflow_dispatch: # Manual start only

jobs:
  activate-rdp:
    runs-on: windows-latest
    timeout-minutes: 360 # 6 hours max
    
    steps:
      # Step 1: Create admin user
      - name: Create Admin Account
        run: |
          net user runneradmin "$env:WIN_PASS" /add /Y
          net localgroup administrators runneradmin /add
        env:
          WIN_PASS: ${{ secrets.WINDOWS_ADMIN_PASSWORD }}
        shell: cmd

      # Step 2: Download cloudflared
      - name: Download Cloudflared
        run: |
          bitsadmin /transfer download /download /priority normal https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe cloudflared.exe

      # Step 3: Start tunnel
      - name: Start Cloudflare Tunnel
        run: |
          start /B cloudflared.exe tunnel --no-autoupdate run --token %CF_TOKEN%
          timeout /t 21600 /nobreak # 6 hours timeout
        env:
          CF_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
        shell: cmd
